import { useEffect, useState } from 'react';
import '../styles/internship.css';
import '../styles/internship-polish.css';
import '../styles/internship-status.css';

type Student = { id: number; nama: string; nim: string };
type Internship = { id: number; mahasiswa_id: number; mahasiswa: Student; perusahaan: string; posisi: string; status: string; catatan: string; dokumen_url: string };
const API_URL = import.meta.env.PUBLIC_API_URL || 'http://localhost:8080';
const statuses = ['diajukan', 'screening', 'diterima', 'ditolak', 'selesai'];

export default function InternshipAdmin() {
  const token = typeof window === 'undefined' ? '' : localStorage.getItem('mhs_token') || '';
  const [items, setItems] = useState<Internship[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [selected, setSelected] = useState<Internship | null>(null);
  const [form, setForm] = useState({ mahasiswa_id: '', perusahaan: '', posisi: '', status: 'diajukan', catatan: '', dokumen: null as File | null });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const headers = { Authorization: `Bearer ${token}` };
  const load = async () => { setLoading(true); try { const [magangResponse, studentResponse] = await Promise.all([fetch(`${API_URL}/magang`, { headers }), fetch(`${API_URL}/mahasiswa`, { headers })]); if (!magangResponse.ok || !studentResponse.ok) throw new Error(); setItems(await magangResponse.json()); setStudents(await studentResponse.json()); } catch { setError('Data proses magang gagal dimuat.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const openNew = () => { setSelected(null); setForm({ mahasiswa_id: '', perusahaan: '', posisi: '', status: 'diajukan', catatan: '', dokumen: null }); setError(''); };
  const openEdit = (item: Internship) => { setSelected(item); setForm({ mahasiswa_id: String(item.mahasiswa_id), perusahaan: item.perusahaan, posisi: item.posisi, status: item.status, catatan: item.catatan, dokumen: null }); setError(''); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const body = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value instanceof File) body.append(key, value); else if (value !== null) body.append(key, String(value)); }); try { const response = await fetch(`${API_URL}/magang${selected ? `/${selected.id}` : ''}`, { method: selected ? 'PUT' : 'POST', headers, body }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Gagal menyimpan'); setMessage('Proses magang berhasil disimpan.'); openNew(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Gagal menyimpan'); } finally { setSaving(false); } };
  return <main className="internship-page"><header className="internship-header"><div><p className="eyebrow">WORKSPACE ADMIN</p><h1>Proses magang</h1><p>Pantau aktivasi dan status pengajuan magang mahasiswa.</p></div><button className="primary-button" onClick={openNew}>+ Proses baru</button></header>{message && <div className="internship-success">{message}</div>}{error && <div className="internship-error">{error}</div>}<div className="internship-layout"><section className="internship-list"><div className="internship-list-head"><h2>Pengajuan terbaru</h2><span>{items.length} proses</span></div>{loading ? <div className="internship-empty">Memuat data...</div> : items.length === 0 ? <div className="internship-empty">Belum ada proses magang.</div> : items.map((item) => <button className={`internship-item ${selected?.id === item.id ? 'selected' : ''}`} key={item.id} onClick={() => openEdit(item)}><span className="internship-avatar">{item.mahasiswa.nama.slice(0, 1)}</span><span><b>{item.mahasiswa.nama}</b><small>{item.mahasiswa.nim} · {item.perusahaan || 'Perusahaan belum diisi'}</small></span><em className={`status-${item.status}`}>{item.status}</em></button>)}</section><section className="internship-form-card"><h2>{selected ? 'Perbarui proses' : 'Upload aktivasi magang'}</h2><p>Data ini akan langsung terlihat pada portal mahasiswa terkait.</p><form onSubmit={save}><label>Mahasiswa<select required value={form.mahasiswa_id} onChange={(event) => setForm({ ...form, mahasiswa_id: event.target.value })} disabled={!!selected}><option value="">Pilih mahasiswa</option>{students.map((student) => <option value={student.id} key={student.id}>{student.nama} · {student.nim}</option>)}</select></label><label>Perusahaan<input value={form.perusahaan} onChange={(event) => setForm({ ...form, perusahaan: event.target.value })} placeholder="Nama perusahaan" /></label><label>Posisi / divisi<input value={form.posisi} onChange={(event) => setForm({ ...form, posisi: event.target.value })} placeholder="Contoh: Software Engineer Intern" /></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label>Catatan<textarea value={form.catatan} onChange={(event) => setForm({ ...form, catatan: event.target.value })} placeholder="Catatan untuk mahasiswa..." /></label><label>Dokumen aktivasi<input type="file" accept=".pdf,.doc,.docx" onChange={(event) => setForm({ ...form, dokumen: event.target.files?.[0] || null })} /></label><button className="primary-button" disabled={saving}>{saving ? 'Menyimpan...' : selected ? 'Simpan perubahan' : 'Upload dan simpan'}</button></form></section></div></main>;
}
