import { useState } from 'react';
import '../styles/admin-settings.css';
import '../styles/admin-settings-polish.css';

type Props = { onBack: () => void; onLogout: () => void };

export default function AdminSettings({ onBack, onLogout }: Props) {
  const [notifications, setNotifications] = useState(true);
  const [compact, setCompact] = useState(false);

  return <main className="settings-shell"><header className="settings-topbar"><button className="settings-back" onClick={onBack}>← <span>Kembali ke overview</span></button><span className="settings-path">Workspace / <b>Pengaturan</b></span></header><section className="settings-content"><div className="settings-heading"><div><p className="eyebrow">SYSTEM PREFERENCES</p><h1>Pengaturan</h1><p>Atur pengalaman kerja admin dan keamanan akun Anda.</p></div><span className="settings-status"><i /> Sistem aktif</span></div><div className="settings-grid"><section className="settings-card profile-settings"><div className="settings-card-title"><div><p className="eyebrow">PROFILE</p><h2>Profil admin</h2></div><span className="settings-avatar">AD</span></div><div className="settings-profile-row"><div><small>Nama</small><strong>Admin Dosen</strong></div><div><small>Email</small><strong>admin@kampus.local</strong></div><div><small>Peran</small><strong>Administrator</strong></div></div></section><section className="settings-card"><div className="settings-card-title"><div><p className="eyebrow">PREFERENCES</p><h2>Preferensi</h2></div><span className="settings-icon">☼</span></div><button className="preference-row" onClick={() => setNotifications(!notifications)}><span><b>Notifikasi proses magang</b><small>Terima pembaruan saat status berubah.</small></span><i className={`toggle ${notifications ? 'on' : ''}`}><em /></i></button><button className="preference-row" onClick={() => setCompact(!compact)}><span><b>Tampilan ringkas</b><small>Gunakan jarak tabel yang lebih padat.</small></span><i className={`toggle ${compact ? 'on' : ''}`}><em /></i></button></section><section className="settings-card security-settings"><div className="settings-card-title"><div><p className="eyebrow">SECURITY</p><h2>Keamanan akun</h2></div><span className="settings-icon">⌁</span></div><div className="security-row"><span><b>Password admin</b><small>Reset password jika Anda lupa atau ingin menggantinya.</small></span><a href="/reset-admin">Reset password</a></div></section><section className="settings-card system-settings"><div className="settings-card-title"><div><p className="eyebrow">SYSTEM STATUS</p><h2>Status sistem</h2></div><span className="settings-icon green-icon">✓</span></div><div className="system-row"><span><i />API server</span><b>Connected</b></div><div className="system-row"><span><i />Database PostgreSQL</span><b>Connected</b></div><div className="system-row"><span><i />Environment</span><b>Development</b></div></section></div><button className="settings-logout" onClick={onLogout}>Keluar dari akun</button></section></main>;
}
